# 异常概述

一个健壮的Java程序在设计时会对可能出现的异常进行处理，如用户输入错误、环境错误、物理限制、设备错误等等....

但是，错误发生的地方，和可能处理错误的地方可能隔了很远，错误发生处的代码也可能不清楚该怎么处理当前的错误。比如在一个方法内发生了错误，如果这样的错误不是在方法内能处理的，就需要通知调用该方法的地方，发生了错误。比如返回一个错误码。

但是，方法不是总有返回值的，返回值的类型也不是固定的。很难通过这种方式统一约定错误码。

所以Java单独提供了一套异常体系和异常处理方式。

异常体系中的类型对象保存了完整的错误信息

通过“抛出”的方式抛出异常对象通知方法的调用方发生了什么异常。

通过异常处理的机制来处理抛出的异常。

# 异常体系

在Java程序设计语言中，异常类型都派生自`Throwable`类，其继承体系如下:

![Throwable](https://gitee.com/wangziming707/note-pic/raw/master/img/Throwable.png)

所有的异常类型都继承自`Throwable`但不会直接继承它，而是继承它的子类`Error`和`Exception`

`Error`类描述的是Java运行时系统的内部错误。应用程序不应该抛出这种类型的对象，(即使抛出，程序也无法处理这样的错误),除了通知用户，并尽力使程序安全地终止之外，我们无法再多做其他事情

`Exception`的层次结构又分解为两个分支：

一个 分支派生于`RuntimeException`表示由程序错误导致的异常，如：错误的类型转换、数组访问越界、访问空指针等

另一个分支则直接继承`Exception`，表示程序本身没有问题，由其他错误引起的异常。 如`IOException`表示的I/O错误、打开一个不存在的文件等

Java语言规范将派生于`Error`类和`RuntimeException`类的所有异常成为非受查(unchecked)异常，所有其他的异常成为受查(checked)异常。

## 自定义异常

在程序中，可能会遇到任何标准异常类都没有充分描述清楚的问题。这种情况下可以创建自定义异常。我们只需要定义一个`Exception`类的子类，或者`Exception`子类的子类。

习惯上，自定义的类应该包含两个构造器，一个默认构造器，一个带有详细描述信息的构造器(超类`Throwable`的`toString`方法将会返回这些详细信息)

例如定义一个`IOException`的子类：

~~~java
public class FileFormatException extends IOException {
    public FileFormatException() {
    }

    public FileFormatException(String message) {
        super(message);
    }
}
~~~

# 异常处理

有了异常体系定义的各种异常后，我们就可以抛出异常、声明异常、处理异常了

## 声明异常

在之前讲述方法的构成时我们说，方法签名由方法名和形参列表构成，实际上除此以外，方法签名还可以有异常声明，以通知方法的调用方该方法可能抛出的异常

通过`throws`子句声明异常，如:

~~~java
public FileInputStream(String name) throws FileNotFoundException{
    ......
}
~~~

如果方法体内有通过`throw`子句抛出受查异常，或者方法体内调用了一个抛出受查异常的方法，则该方法必须通过`throws`子句声明这些可能抛出的异常；否则编译器将报错。

当然也可以声明非受查异常，但是不应该这样做，因为:

* 对于`Error` 类型的非受查异常:程序代码对`Error`的异常是无法处理的，而且任何程序代码都具有抛出`Error`异常的可能

* 对`RuntimeException`类型的非受查异常，它完全在我们的控制之下，能够通过修改程序避免。

总之，一个方法必须声明所有可能抛出的受查异常， 而非受查异常要么不可控制（`Error`),要么就应该避免发生 （ `RuntimeException `)  

### 声明多个异常

如果一个方法有可能抛出多个受查异常类型， 那么就必须在方法的首部声明所有的异常类。每个异常类之间用逗号隔开，如:

~~~java
public Image loadlmage(String s) throws FileNotFoundException, EOFException{
    //......
}
~~~

如果抛出了多个异常，也可以通过声明它们的父类来替代所有的异常，当然，并不推荐这样做。

### 覆盖中的异常声明

如果在子类中覆盖了超类的一个方法， 子类方法中声明的受查异常不能比超类方法中声明的异常更通用，这体现在:

子类方法只能声明父类中已经声明的异常或异常的子类

## 抛出异常

在方法中，通过`throw`关键字抛出异常:

~~~java
throw throwableObject; //throwableObject是异常对象
~~~

例如：

~~~java
throw new IOException();
//或者
EOFException e = new EOFException();
throw e;
~~~

注意`throw`子句只能写在方法体内部，并且如果抛出的异常是受查异常，则方法必须声明该异常。

如果方法程序运行到throw子句，那么该方法就不会返回给调用者，而是抛出该异常给调用者，让调用者(或者调用者的调用者)处理该异常

## 捕获异常

如果某个异常发生后没有在任何地方进行捕获，那么这个异常最终将通过主函数抛给虚拟机，虚拟机将终止程序并在控制台打印异常信息(包括异常的类型和堆栈内容)

通过`try/catch`语句块捕获程序中的异常，其简单格式如下:

~~~java
try{
    //可能抛出异常的代码
}catch(ExceptionType e){ 
    //异常处理器代码
}
~~~

如果在`try `语句块中的任何代码抛出的异常类是在`catch`子句中说明的异常类或者其子类,那么：

* 程序将跳过`try`语句块的其余代码
* 程序将执行`catch`子句中的处理器代码



### 捕获多个异常

在一个`try`语句块中可以捕获多个异常类型，并对不同类型的异常做出不同的处理:

~~~java
try {
    //可能抛出异常的代码
} catch (Exception1 e ){
    //异常处理器代码
} catch (Exception2 e) {
    //异常处理器代码
} ...
~~~

如果多个异常类型的处理方式一样，也可以在同一个catch子句中捕获多个异常类型：

~~~java
try {
    //可能抛出异常的代码
} catch (Exception1 |Exception2 e ){
    //异常处理器代码
}
~~~

当在同一个catch子句捕获多个异常时,异常变量`e`隐含为`final`变量

### 异常链

在`Throwable`类中维护了如下属性：

~~~java
private Throwable cause = this;
~~~

`cause`也是一个可抛出的异常，表示导致该异常被抛出的原始异常。

在`catch`语句中可再次抛出异常，在抛出异常时，最好使用`initCause`方法设置导致该异常被抛出的异常，这样最终处理异常时，能够获取到完整的异常链,例如:

~~~java
try {
    //access database
} catch (SQLException e){
    throw new ServletException("database error").initCause(e);
}
~~~

通过`initCause`指示了新抛出的`ServletException`是由`SQLException`引起的，此时打印异常信息会展示异常链:

~~~java
Exception in thread "main" com.wzm.base.ServletException: database error
	at com.wzm.base.App.main(App.java:20)
Caused by: java.sql.SQLException
	at com.wzm.base.App.main(App.java:18)
~~~

使用这种包装技术，可以让用户抛出高级异常，而不会丢失原始异常的细节。

### finally子句

有些时候，不论是正常执行，还是发生了异常，在退出方法前都希望执行的代码；比如资源的回收，可以使用finally子句:

~~~JAVA
try{
    //可能发生异常的代码
}catch( E e){
    //处理异常
}finally{
    //不管是否发生异常都会执行的代码
}
~~~

这样不管是否有异常被捕获，finally 子句中的代码都被执行

`try`语句可以只有`finally`子句，而没有`catch`语句：

~~~java
try{
    //....
}finally{
    //不管是否发生异常都会执行的代码
}
~~~

如果`try`语句中有`return`语句，执行该语句不会直接退出方法，而是会先执行完`finally`代码块再退出方法,如果`finally`语句中也有`return`语句，那么`finally`语句中的`return `值将覆盖原先的返回值

### 带资源的try语句

有时候finally语句块中关闭资源的`close`方法也可能抛出异常，那么就要在finally代码块中再使用`try/catch`语句捕获`close`方法抛出的异常，代码将变得异常繁琐

为此，Java提供了带资源的try语句:

~~~java
try(Resource res = ...){
    //使用res和其他内容
}
~~~

`()`中的对象类型必须实现`AutoCloseable`，再`try`语句块退出时，会自动调用`res.close()`方法,例如:

~~~~~java
try (Scanner in = new Scanner(new FileInputStream("path")), "UTF-8"){
	while (in.hasNext())
		System.out.println(in.next());
}
~~~~~

不论是正常退出，还是抛出了异常，都将调用`in.close()`方法

在`try()`中可以指定多个资源。

带资源的 try语句自身也可以有 catch 子句和一个 finally 子句。这些子句会在关闭资源之后执行。  

# 断言

假设确信某个属性符合要求，并且代码的执行依赖这个属性

断言使用关键字`assert`，使用格式为:

~~~java
assert 条件;
assert 条件:表达式;
~~~

这两种形式都会对条件进行检测，如果结果为`false`则抛出一个`AssertionError`异常。在第二种形式中，表达式将被传入`AssertionError`的构造器，并转换成一个消息字符串。

例如:

~~~java
assert x>=0:x;
~~~

## 启用和禁用断言

在默认情况下，断言被禁用，可以在运行程序时用`-emableassertions`或`-ea`选项启用，如:

~~~
java -enableassertions MyApp
~~~

启用或禁用断言时不必重新编译程序。启用或禁用断言是类加载器( class loader) 的功能  

也可以在某个类或整个包中使用断言， 例如：

~~~ 
java -ea:MyClass -ea:com..mycompany.mylib.. , MyApp  
~~~

也可以用选项 -disableassertions 或 -da 禁用某个特定类和包的断言：

~~~ 
java -ea:... -da:MyClass MyApp  
~~~

然而， 启用和禁用所有断言的` -ea `和 `-da `开关不能应用到那些没有类加载器的“ 系统类”上。对于这些系统类来说， 需要使用`-enablesystemassertions/-esa` 开关启用断言  

